Repository ovh/ovh-ui-kit, pull requests merged in 2018-07, with the labels that each got.

#213 feat(oui-progress): progress component upgrade
  packages/oui-progress/README.md
  packages/oui-progress/_mixins.less
  packages/oui-progress/_normalize.less
  packages/oui-progress/_variables.less
  packages/oui-progress/progress.less
Labels: cui migration, feature, quality check

#211 feat(oui-switch): add new oui-switch styles
  packages/oui-field/_mixins.less
  packages/oui-field/field.less
  packages/oui-switch/README.md
  packages/oui-switch/_mixins.less
  packages/oui-switch/_variables.less
  packages/oui-switch/switch.less
Labels: feature, quality check ok

#240 fix(oui-input-group): fix clipboard tooltips in datagrids
  packages/oui-input-group/_mixins.less
Labels: bug

#241 fix(oui-popover): update style to specs
  packages/oui-popover/popover.less
Labels: bug

#245 feat(oui-tile): handle icon for external link in tile button
  packages/oui-button/_mixins.less
  packages/oui-button/button.less
  packages/oui-tile/tile.less
Labels: enhancement

#246 feat(oui-navbar): add new components
  packages/oui-navbar/_mixins.less
  packages/oui-navbar/_normalize.less
  packages/oui-navbar/_variables.less
  packages/oui-navbar/navbar.less
  packages/oui-switch/_variables.less
  packages/oui-tooltip/_mixins.less
  packages/oui-tooltip/tooltip.less
Labels: feature

#247 feat(oui-tile): add disabled on oui-tile-button
  packages/oui-button/button.less
  packages/oui-tile/tile.less
Labels: feature
