Repository ovh/ovh-ui-kit, pull requests merged in 2018-12, with the labels that each got.

#314 fix(oui-icons): fix dist icons path
  package.json
  packages/oui/_dist.less
Labels: bug

#312 feat(oui-file): add file component
  packages/oui-file/_normalize.less
  packages/oui-file/_variables.less
  packages/oui-file/file.less
  packages/oui/_settings.less
  packages/oui/stylekit.less
Labels: feature

#318 refactor(oui-select): use ui-select in a proper way
  packages/oui-field/_mixins.less
  packages/oui-field/field.less
  packages/oui-select-picker/_mixins.less
  packages/oui-select/_mixins.less
  packages/oui-select/_variables.less
  packages/oui-ui-select/_mixins.less
  packages/oui-ui-select/_normalize.less
  packages/oui-ui-select/_variables.less
  packages/oui-ui-select/ui-select.less
Labels: enhancement, quality check

#320 fix(oui-navbar): have menu items have own line height
  packages/oui-navbar/_variables.less
  packages/oui-navbar/navbar.less
Labels: bug, quality check

#324 feat(oui-select): add multiple selection
  packages/oui-chip/_variables.less
  packages/oui-chip/chip.less
  packages/oui-ui-select/_variables.less
  packages/oui-ui-select/ui-select.less
Labels: feature
