Repository ovh/ovh-ui-kit, pull requests merged in 2018-10, with the labels that each got.

#282 Fix/default style
  packages/oui-back-button/README.md
  packages/oui-list/_mixins.less
  packages/oui-list/_normalize.less
  packages/oui-list/_variables.less
  packages/oui-select/_mixins.less
  packages/oui-switch/switch.less
  packages/oui-textarea/_mixins.less
  packages/oui-textarea/_normalize.less
  packages/oui-themes/README.txt
  packages/oui-themes/diamond/_mixins.less
  packages/oui-themes/sapphire/_mixins.less
  packages/oui-themes/themes.less
  packages/oui-tile/README.md
  packages/oui-typography/README.md
  packages/oui-typography/_mixins.less
  packages/oui-typography/_variables.less
  packages/oui-typography/typography.less
  packages/oui/stylekit.less
Labels: bug, enhancement

#285 fix: fix reboot style
  packages/oui-status/status.less
  packages/oui-typography/_variables.less
  packages/oui-typography/typography.less
  packages/oui/_reboot.less
  packages/oui/_settings.less
  packages/oui/stylekit.less
Labels: bug

#289 perf(oui-typography): replace woff/woff2 fonts generated from TTF instead of OTF
  packages/oui-typography/fonts/source-sans-pro/black/SourceSansPro-Black.woff
  packages/oui-typography/fonts/source-sans-pro/black/SourceSansPro-Black.woff2
  packages/oui-typography/fonts/source-sans-pro/black/SourceSansPro-BlackIt.woff
  packages/oui-typography/fonts/source-sans-pro/black/SourceSansPro-BlackIt.woff2
  packages/oui-typography/fonts/source-sans-pro/bold/SourceSansPro-Bold.woff
  packages/oui-typography/fonts/source-sans-pro/bold/SourceSansPro-Bold.woff2
  packages/oui-typography/fonts/source-sans-pro/bold/SourceSansPro-BoldIt.woff
  packages/oui-typography/fonts/source-sans-pro/bold/SourceSansPro-BoldIt.woff2
  packages/oui-typography/fonts/source-sans-pro/extra-light/SourceSansPro-ExtraLight.woff
  packages/oui-typography/fonts/source-sans-pro/extra-light/SourceSansPro-ExtraLight.woff2
  packages/oui-typography/fonts/source-sans-pro/extra-light/SourceSansPro-ExtraLightIt.woff
  packages/oui-typography/fonts/source-sans-pro/extra-light/SourceSansPro-ExtraLightIt.woff2
  packages/oui-typography/fonts/source-sans-pro/light/SourceSansPro-Light.woff
  packages/oui-typography/fonts/source-sans-pro/light/SourceSansPro-Light.woff2
  packages/oui-typography/fonts/source-sans-pro/light/SourceSansPro-LightIt.woff
  packages/oui-typography/fonts/source-sans-pro/light/SourceSansPro-LightIt.woff2
  packages/oui-typography/fonts/source-sans-pro/regular/SourceSansPro-It.woff
  packages/oui-typography/fonts/source-sans-pro/regular/SourceSansPro-It.woff2
  packages/oui-typography/fonts/source-sans-pro/regular/SourceSansPro-Regular.woff
  packages/oui-typography/fonts/source-sans-pro/regular/SourceSansPro-Regular.woff2
  packages/oui-typography/fonts/source-sans-pro/semibold/SourceSansPro-Semibold.woff
  packages/oui-typography/fonts/source-sans-pro/semibold/SourceSansPro-Semibold.woff2
  packages/oui-typography/fonts/source-sans-pro/semibold/SourceSansPro-SemiboldIt.woff
  packages/oui-typography/fonts/source-sans-pro/semibold/SourceSansPro-SemiboldIt.woff2
Labels: enhancement

#290 fix: add missing form controls
  packages/oui/_settings.less
Labels: bug

#292 fix(oui-datagrid): fix sticky columns
  packages/oui-datagrid/_mixins.less
Labels: bug

#293 fix: fix default style for custom tags
  packages/oui-collapsible/_normalize.less
  packages/oui-criteria-adder/_normalize.less
  packages/oui-criteria-adder/criteria-adder.less
  packages/oui-datagrid/_normalize.less
  packages/oui-field/_normalize.less
  packages/oui-guide-menu/guide-menu.less
  packages/oui-header-tabs/header-tabs.less
  packages/oui-input-group/_normalize.less
  packages/oui-input-group/input-group.less
  packages/oui-message/_normalize.less
  packages/oui-page-header/_normalize.less
  packages/oui-pagination/_normalize.less
  packages/oui-pagination/pagination.less
  packages/oui-radio-toggle-group/_normalize.less
  packages/oui-radio/_normalize.less
  packages/oui-select-picker/_normalize.less
  packages/oui-select/_normalize.less
  packages/oui-skeleton/_normalize.less
  packages/oui-skeleton/skeleton.less
  packages/oui-spinner/_normalize.less
  packages/oui-spinner/spinner.less
  packages/oui-switch/_normalize.less
  packages/oui-switch/switch.less
  packages/oui-textarea/_normalize.less
Labels: bug

#300 feat(oui-popover): add animation on opening
  packages/oui-message/_mixins.less
  packages/oui-modal/_mixins.less
  packages/oui-popover/_normalize.less
  packages/oui-popover/_variables.less
  packages/oui-popover/popover.less
Labels: enhancement

#301 style(oui-calendar): update timepicker style to specs
  packages/oui-calendar/_normalize.less
  packages/oui-calendar/_variables.less
Labels: enhancement
