Repository ovh/ovh-ui-kit, pull requests merged in 2018-04, with the labels that each got.

#184 feat(oui-popover): add new Popover component styles
  packages/oui-popover/README.md
  packages/oui-popover/_normalize.less
  packages/oui-popover/_variables.less
  packages/oui-popover/popover.less
  packages/oui/stylekit.less
Labels: feature, ok for merge, quality check ok

#181 feat(oui-status): add new oui-status
  packages/oui-status/README.md
  packages/oui-status/_normalize.less
  packages/oui-status/status.less
  packages/oui/stylekit.less
Labels: feature, quality check

#188 fix(oui-select-picker): add missing focus style on select
  packages/oui-select-picker/_mixins.less
Labels: enhancement

#187 feat(oui-typography): add modifier to icon link
  packages/oui-typography/README.md
  packages/oui-typography/_mixins.less
  packages/oui-typography/_variables.less
  packages/oui-typography/typography.less
Labels: enhancement

#191 fix(oui-select): fix dropdown min-width
  packages/oui-ui-select/_mixins.less
Labels: enhancement

#192 fix(oui-textarea): fix disable state in fieldset
  packages/oui-textarea/README.md
  packages/oui-textarea/_mixins.less
  packages/oui-textarea/textarea.less
Labels: enhancement

#193 feat(oui-field): add class container for label popover
  packages/oui-field/_mixins.less
Labels: feature

#182 feat(oui-progress-tracker): change style according to ui-spec
  packages/oui-progress-tracker/README.md
  packages/oui-progress-tracker/_mixins.less
  packages/oui-progress-tracker/_variables.less
  packages/oui-progress-tracker/progress-tracker-background.png
  packages/oui-progress-tracker/progress-tracker-background.svg
Labels: enhancement, ok for merge, question

#198 feat(oui-color): new colors addition
  packages/oui-button/_variables.less
  packages/oui-color-badge/_variables.less
  packages/oui-color/README.md
  packages/oui-color/_constants.less
  packages/oui-datagrid/_variables.less
  packages/oui-input/_variables.less
  packages/oui-navbar/_variables.less
  packages/oui-select/_mixins.less
  packages/oui-textarea/_variables.less
  packages/oui-thumbnail/_variables.less
  packages/oui-ui-select/_variables.less
Labels: feature, ok for merge
