Repository ovh/ovh-ui-kit, pull requests merged in 2018-06, with the labels that each got.

#197 feat(oui-collapsible): collapsible component addition
  packages/oui-collapsible/README.md
  packages/oui-collapsible/_normalize.less
  packages/oui-collapsible/_variables.less
  packages/oui-collapsible/collapsible.less
  packages/oui/stylekit.less
Labels: cui migration, feature, ok for merge, quality check ok

#209 Feature/oui skeleton
  packages/oui-skeleton/README.md
  packages/oui-skeleton/_mixins.less
  packages/oui-skeleton/_variables.less
  packages/oui-skeleton/skeleton.less
  packages/oui/stylekit.less
Labels: cui migration, feature, ok for merge, quality check ok

#200 Feature/oui clipboard
  packages/oui-input-group/input-group.less
Labels: cui migration, feature, quality check

#208 feat(oui-slideshow): add new Slideshow Component
  packages/oui-slideshow/_normalize.less
  packages/oui-slideshow/_variables.less
  packages/oui-slideshow/slideshow.less
  packages/oui/stylekit.less
Labels: feature, quality check ok

#218 fix(oui-slideshow): fix naming
  packages/oui-slideshow/_normalize.less
  packages/oui-slideshow/slideshow.less
Labels: enhancement

#214 feat(oui-datagrid): add styles for datagrid parameters
  dist/icons/icons.eot
  dist/icons/icons.svg
  dist/icons/icons.ttf
  dist/icons/icons.woff
  dist/icons/icons.woff2
  packages/oui-datagrid/datagrid.less
  packages/oui-icons/README.md
  packages/oui-icons/_icons.less
  packages/oui-icons/svg/gear.svg
Labels: feature

#219 feat(oui-page-header): create style
  packages/oui-page-header/README.md
  packages/oui-page-header/_normalize.less
  packages/oui-page-header/_variables.less
  packages/oui-page-header/page-header.less
  packages/oui/stylekit.less
Labels: feature, ok for merge, quality check ok

#215 refactor: update oui-dropdown for action-menu and guide-menu
  packages/oui-action-menu/README.md
  packages/oui-action-menu/_mixins.less
  packages/oui-action-menu/_variables.less
  packages/oui-action-menu/action-menu.less
  packages/oui-button/_mixins.less
  packages/oui-button/_variables.less
  packages/oui-button/button.less
  packages/oui-calendar/_normalize.less
  packages/oui-calendar/_variables.less
  packages/oui-dropdown/README.md
  packages/oui-dropdown/_mixins.less
  packages/oui-dropdown/_normalize.less
  packages/oui-dropdown/_variables.less
  packages/oui-dropdown/dropdown.less
  packages/oui-select-picker/_variables.less
  packages/oui/stylekit.less
Labels: enhancement, quality check ok

#217 feat(oui-tile): create component
  packages/oui-tile/README.md
  packages/oui-tile/_normalize.less
  packages/oui-tile/_variables.less
  packages/oui-tile/tile.less
  packages/oui/stylekit.less
Labels: feature, quality check ok

#220 feat(oui-guide-menu): create component
  packages/oui-guide-menu/_normalize.less
  packages/oui-guide-menu/_variables.less
  packages/oui-guide-menu/guide-menu.less
  packages/oui-page-header/page-header.less
  packages/oui/stylekit.less
Labels: feature, quality check ok

#221 feat(oui-header-tabs): add oui-header-tabs feature
  packages/oui-header-tabs/README.md
  packages/oui-header-tabs/_normalize.less
  packages/oui-header-tabs/header-tabs.less
  packages/oui/stylekit.less
Labels: feature

#222 refactor(oui-header-tabs): header-tabs improvements
  packages/oui-header-tabs/header-tabs.less
Labels: enhancement

#223 refactor(oui-header-tabs): header-tabs improvements
  packages/oui-header-tabs/header-tabs.less
Labels: enhancement

#225 fix(oui-page-header): fix new styles responsive detection
  packages/oui-guide-menu/guide-menu.less
  packages/oui-page-header/page-header.less
Labels: bug

#230 refactor(oui-header-tabs): add disabled flag on items
  packages/oui-header-tabs/header-tabs.less
Labels: enhancement, quality check ok

#232 style(oui-tile): center spinner
  packages/oui-tile/tile.less
Labels: bug

#231 feat(oui-typography): add abbr style from specs
  packages/oui-typography/README.md
  packages/oui-typography/typography.less
Labels: feature

#235 fix(oui-tile): fix normalize for height sizing
  packages/oui-tile/_normalize.less
Labels: bug
