Repository ovh/ovh-ui-kit, pull requests merged in 2018-11, with the labels that each got.

#302 feat(oui-inline-adder): add inline-adder component
  packages/oui-field/_mixins.less
  packages/oui-inline-adder/_normalize.less
  packages/oui-inline-adder/inline-adder.less
  packages/oui/stylekit.less
Labels: feature

#303 fix(oui-status): set border to none when it's used on a button element
  packages/oui-status/status.less
Labels: bug, enhancement

#307 feat(oui-dual-list): add dual-list component
  packages/oui-button/_mixins.less
  packages/oui-collapsible/collapsible.less
  packages/oui-dual-list/_normalize.less
  packages/oui-dual-list/_variables.less
  packages/oui-dual-list/dual-list.less
  packages/oui/stylekit.less
Labels: feature

#308 feat(oui-icons): added domain-dns icon
  packages/oui-icons/README.md
  packages/oui-icons/_icons.less
  packages/oui-icons/svg/domain-dns.svg
Labels: feature, quality check

#310 feat(oui-autocomplete): add autocomplete directive
  packages/oui-autocomplete/autocomplete.less
  packages/oui-dropdown/_variables.less
  packages/oui/stylekit.less
Labels: feature, quality check ok

#311 feat(oui-tabs): add tabs component
  packages/oui-tabs/_normalize.less
  packages/oui-tabs/_variables.less
  packages/oui-tabs/tabs.less
  packages/oui/stylekit.less
Labels: feature, quality check ok
