Repository ovh/ovh-ui-kit, pull requests merged in 2018-02, with the labels that each got.

#149 fix(action-menu): fix text color of disabled items
  packages/oui-action-menu/_mixins.less
Labels: enhancement, quality check

#148 fix(datagrid): remove relative position in datagrid cells
  packages/oui-datagrid/_mixins.less
Labels: bug, ok for merge, quality check ok

#150 style(navbar): update colors for menu items
  packages/oui-navbar/_mixins.less
  packages/oui-navbar/_variables.less
Labels: enhancement, ok for merge, quality check ok

#145 feat(ui-select): add styles for ui-select
  packages/oui-button/_mixins.less
  packages/oui-button/_variables.less
  packages/oui-ui-select/_mixins.less
  packages/oui-ui-select/_normalize.less
  packages/oui-ui-select/_variables.less
  packages/oui-ui-select/ui-select.less
  packages/oui/stylekit.less
Labels: feature, ok for merge, quality check ok

#147 feat(textarea): add new component
  packages/oui-textarea/README.md
  packages/oui-textarea/_mixins.less
  packages/oui-textarea/_variables.less
  packages/oui-textarea/textarea.less
Labels: feature, quality check ok
