Repository ovh/ovh-ui-kit, pull requests merged in 2018-05, with the labels that each got.

#196 fix(oui-textarea): fix slow resizing
  packages/oui-textarea/_mixins.less
Labels: bug, ok for merge

#199 feat(oui-icons): add shape circle and dot icon
  packages/oui-icons/README.md
  packages/oui-icons/_icons.less
  packages/oui-icons/svg/clock-wait.svg
  packages/oui-icons/svg/shape-circle.svg
  packages/oui-icons/svg/shape-dot.svg
Labels: feature, ok for merge

#203 chore(oui-datagrid): fix syntax
  packages/oui-datagrid/_mixins.less
Labels: enhancement, ok for merge

#202 Style/update progress tracker
  packages/oui-progress-tracker/README.md
  packages/oui-progress-tracker/_mixins.less
  packages/oui-progress-tracker/_variables.less
  packages/oui-progress-tracker/progress-tracker.less
Labels: enhancement, ok for merge

#207 style(oui-navbar): add style for brand title
  packages/oui-navbar/_mixins.less
  packages/oui-navbar/_variables.less
Labels: enhancement, ok for merge

#189 feat(oui-navbar): add style of notifications
  packages/oui-navbar/_mixins.less
  packages/oui-navbar/_variables.less
  packages/oui-navbar/navbar.less
Labels: enhancement, ok for merge

#212 chore(oui-calendar): bump version of flatpickr to v4.5.0
  package.json
Labels: bug
