Repository ovh/ovh-ui-kit, pull requests merged in 2018-09, with the labels that each got.

#263 refactor(oui-icons): keep only woff & woff2 on generated fonts
  dist/icons/icons.css
  dist/icons/icons.eot
  dist/icons/icons.html
  dist/icons/icons.svg
  dist/icons/icons.ttf
  dist/oui.css
  package.json
  packages/oui-icons/fonts.less
Labels: enhancement

#264 fix: fix for LESS v3
  package.json
  packages/oui-checkbox/_mixins.less
  packages/oui-checkbox/_variables.less
  packages/oui-criteria-adder/criteria-adder.less
  packages/oui-datagrid/_mixins.less
  packages/oui-datagrid/_variables.less
  packages/oui-datagrid/datagrid.less
  packages/oui-icons/icons.less
  packages/oui-radio/_mixins.less
  packages/oui-select/_mixins.less
  packages/oui/_settings.less
  yarn.lock
Labels: bug

#270 feat(oui-sidebar): add sidebar style
  packages/oui-navbar/navbar.less
  packages/oui-sidebar/README.md
  packages/oui-sidebar/_variables.less
  packages/oui-sidebar/sidebar.less
  packages/oui/stylekit.less
Labels: feature

#273 chore: update dependencies
  package.json
  yarn.lock
Labels: enhancement
