Repository ovh/ovh-ui-kit, pull requests merged in 2018-03, with the labels that each got.

#158 style(oui-search): add variant oui-input-group-search
  packages/oui-input-group/_mixins.less
  packages/oui-input-group/_variables.less
  packages/oui-input-group/input-group.less
  packages/oui-input/README.md
  packages/oui-input/_mixins.less
  packages/oui-input/_variables.less
Labels: feature

#159 chore: commitlint, commitizen and conventional-changelog integration
  .scriptsrc
  CHANGELOG.md
  CONTRIBUTING.md
  commitlint.config.js
  package.json
  yarn.lock
Labels: enhancement

#166 feat(oui-chip): add chip component style
  packages/oui-chip/README.md
  packages/oui-chip/_normalize.less
  packages/oui-chip/_variables.less
  packages/oui-chip/chip.less
  packages/oui/stylekit.less
Labels: feature

#175 fix(oui-back-button): fix arrow color to be the same as a link
  packages/oui-button/_variables.less
Labels: bug

#177 chore(oui-calendar): remove flatpickr import
  package.json
  packages/oui-calendar/_normalize.less
  yarn.lock
Labels: bug
