Repository ovh/ovh-ui-kit, pull requests merged in 2019-07, with the labels that each got.

#462 feat(oui-datagrid): add expandable row detail
  .gitignore
  packages/apps/workshop/stories/components/datagrid.stories.js
  packages/base/core/src/less/_variables.less
  packages/components/datagrid/README.md
  packages/components/datagrid/src/index.js
  packages/components/datagrid/src/js/datagrid.controller.js
  packages/components/datagrid/src/js/datagrid.html
  packages/components/datagrid/src/js/datagrid.spec.js
  packages/components/datagrid/src/js/row-detail/datagrid-row-detail.component.js
  packages/components/datagrid/src/js/row-detail/datagrid-row-detail.controller.js
  packages/components/datagrid/src/less/datagrid.less
Labels: enhancement

#465 fix(datagrid): typo on class selector
  packages/components/datagrid/src/less/datagrid.less
Labels: bug

#467 fix(oui-datagrid): reflect scope change on row detail item
  packages/components/datagrid/src/js/row-detail/datagrid-row-detail.controller.js
Labels: bug

#475 feat(tile): add transclude for term and actions
  packages/apps/workshop/stories/components/tile.stories.js
  packages/components/tile/README.md
  packages/components/tile/src/js/definition/tile-definition.component.js
  packages/components/tile/src/js/definition/tile-definition.controller.js
  packages/components/tile/src/js/definition/tile-definition.html
  packages/components/tile/src/js/tile.spec.js
Labels: feature

#476 feat(criteria): add ability to hide operators field
  packages/apps/workshop/stories/_data/criteria.data.json
  packages/components/criteria/README.md
  packages/components/criteria/src/js/adder/criteria-adder.html
  packages/components/criteria/src/js/adder/criteria-adder.spec.data.json
  packages/components/criteria/src/js/adder/criteria-adder.spec.js
Labels: feature
