Repository ovh/ovh-ui-kit, pull requests merged in 2019-09, with the labels that each got.

#499 fix(oui-dropdown): display button when item has href and is disabled
  packages/components/dropdown/src/js/item/dropdown-item.html
Labels: bug

#500 fix(oui-dropdown): remove one time binding of href attribute
  packages/components/dropdown/README.md
  packages/components/dropdown/src/js/item/dropdown-item.html
Labels: bug

#504 feat(oui-navbar): allow to create link as menu header
  packages/components/navbar/README.md
  packages/components/navbar/src/js/menu/navbar-menu.component.js
  packages/components/navbar/src/js/menu/navbar-menu.html
  packages/components/navbar/src/js/navbar.spec.js
Labels: feature

#509 build: fix object spread operator compatibility on edge
  packages/apps/workshop/.storybook/webpack.config.js
  packages/base/config/package.json
  packages/base/config/src/webpack.rules.js
  yarn.lock
Labels: bug

#503 feat(button): apply ODS theme for secondary & link variant
  packages/apps/workshop/stories/components/button-native.stories.js
  packages/apps/workshop/stories/components/button-webcomponent.stories.js
  packages/apps/workshop/stories/old/components/button.stories.js
  packages/apps/workshop/stories/old/styles/button.stories.js
  packages/apps/workshop/stories/old/styles/sidebar.stories.js
  packages/base/core/src/less/_variables.less
  packages/components/button/src/less/button.less
  packages/components/form-actions/src/js/form-actions.html
  packages/components/form-actions/src/js/form-actions.spec.js
  packages/components/navbar/src/js/menu/navbar-menu.html
  packages/components/pagination/src/js/pagination.html
  packages/components/pagination/src/less/pagination.less
  packages/components/stepper/src/js/step-form/step-form.html
  packages/components/stepper/src/js/stepper.spec.js
  packages/components/tile/src/js/button/tile-button.html
  packages/components/tile/src/less/tile.less
Labels: enhancement, quality check ok

#506 feat(status): apply ODS theme & add small size
  packages/apps/workshop/stories/components/status-native.stories.js
  packages/apps/workshop/stories/old/styles/status.stories.js
  packages/base/core/src/less/_tokens.less
  packages/base/core/src/less/_variables.less
  packages/components/status/src/less/status.less
Labels: enhancement, quality check ok

#507 feat(box): apply ODS theme
  packages/apps/workshop/stories/components/box.stories.js
  packages/base/core/src/less/_variables.less
  packages/components/box/src/less/box.less
Labels: enhancement, quality check ok
