Repository ovh/ovh-ui-kit, pull requests merged in 2019-10, with the labels that each got.

#514 fix(oui-numeric): allow custom min and max values
  packages/components/numeric/src/js/numeric.controller.js
  packages/components/numeric/src/js/numeric.spec.js
Labels: bug

#520 feat(oui-select-picker) add footer and picture transclude
  packages/oui-select-picker/_mixins.less
  packages/oui-select-picker/_variables.less
Labels: feature

#519 feat(typography): add description horizontal
  packages/apps/workshop/stories/content/typography.stories.js
  packages/base/core/src/less/_variables.less
  packages/base/core/src/less/typography.less
Labels: feature

#522 feat(oui-typography): backport description horizontal
  packages/oui-typography/_variables.less
  packages/oui-typography/typography.less
Labels: feature

#523 fix(oui-header-tabs): fix style of active item
  packages/oui-header-tabs/_normalize.less
  packages/oui-header-tabs/_variables.less
  packages/oui-header-tabs/header-tabs.less
Labels: bug

#524 fix(field): checkAllErrors avoid undefined value
  packages/components/field/src/js/field.controller.js
Labels: bug

#528 feat(oui-criteria-adder): add button description
  packages/components/criteria/README.md
  packages/components/criteria/src/js/adder/criteria-adder.html
  packages/components/criteria/src/js/adder/criteria-adder.provider.js
  packages/components/criteria/src/js/adder/criteria-adder.spec.js
Labels: enhancement

#512 feat(tabs): apply ODS theme
  packages/apps/workshop/stories/components/tabs.stories.js
  packages/base/core/src/less/_variables.less
  packages/components/tabs/README.md
  packages/components/tabs/src/js/item/tabs-item.component.js
  packages/components/tabs/src/js/item/tabs-item.controller.js
  packages/components/tabs/src/js/item/tabs-item.html
  packages/components/tabs/src/js/tabs.html
  packages/components/tabs/src/js/tabs.spec.js
  packages/components/tabs/src/less/tabs.less
Labels: feature, quality check

#529 fix(header-tabs): fix scrolling in responsive
  packages/components/header/src/js/tabs/header-tabs.controller.js
Labels: bug

#531 fix(oui-select-picker): fix footer placement with dynamic height
  packages/oui-select-picker/_mixins.less
Labels: bug

#532 feat(header-tabs): update tabs scrolling to allow scroll tab by tab
  packages/apps/workshop/stories/components/header.stories.js
  packages/components/header/src/js/tabs/header-tabs.controller.js
  packages/components/header/src/js/tabs/header-tabs.html
  packages/components/header/src/js/tabs/header-tabs.spec.js
  packages/components/header/src/less/header-tabs.less
Labels: enhancement
