Repository ovh/ovh-ui-kit, pull requests merged in 2019-05, with the labels that each got.

#394 feat(oui-navbar): add style for menu header container
  packages/oui-navbar/navbar.less
Labels: feature

#401 fix(button): fix icon color when disabled
  packages/apps/workshop/package.json
  packages/base/core/src/less/icons.less
  packages/components/button/src/less/_mixins.less
  yarn.lock
Labels: bug

#399 docs(tabs): set right type to the checked attribute
  packages/components/tabs/README.md
Labels: enhancement

#397 fix(clipboard): set button type
  packages/components/clipboard/src/js/clipboard.html
Labels: bug

#395 feat(core): add extra thin icons to 'Oui Icons' font
  packages/apps/workshop/stories/content/icons.stories.js
  packages/base/core/src/fonts/oui-icons/oui-icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.html
  packages/base/core/src/fonts/oui-icons/oui-icons.json
  packages/base/core/src/fonts/oui-icons/oui-icons.woff
  packages/base/core/src/fonts/oui-icons/oui-icons.woff2
  packages/base/core/src/less/_icons.less
  packages/base/core/src/svg/thin/arrow-down_extra-thin.svg
  packages/base/core/src/svg/thin/arrow-left_extra-thin.svg
  packages/base/core/src/svg/thin/arrow-right_extra-thin.svg
  packages/base/core/src/svg/thin/arrow-up_extra-thin.svg
  packages/base/core/src/svg/thin/bell_extra-thin.svg
  packages/base/core/src/svg/thin/bin_extra-thin.svg
  packages/base/core/src/svg/thin/calendar_extra-thin.svg
  packages/base/core/src/svg/thin/chat_extra-thin.svg
  packages/base/core/src/svg/thin/chevron-down_extra-thin.svg
  packages/base/core/src/svg/thin/chevron-left_extra-thin.svg
  packages/base/core/src/svg/thin/chevron-right_extra-thin.svg
  packages/base/core/src/svg/thin/chevron-up-down_extra-thin.svg
  packages/base/core/src/svg/thin/chevron-up_extra-thin.svg
  packages/base/core/src/svg/thin/close_extra-thin.svg
  packages/base/core/src/svg/thin/ellypsis-vertical_extra-thin.svg
  packages/base/core/src/svg/thin/ellypsis_extra-thin.svg
  packages/base/core/src/svg/thin/eye-closed_extra-thin.svg
  packages/base/core/src/svg/thin/eye-open_extra-thin.svg
  packages/base/core/src/svg/thin/file_extra-thin.svg
  packages/base/core/src/svg/thin/filex2_extra-thin.svg
  packages/base/core/src/svg/thin/folder_extra-thin.svg
  packages/base/core/src/svg/thin/hamburger_extra-thin.svg
  packages/base/core/src/svg/thin/home_extra-thin.svg
  packages/base/core/src/svg/thin/info_extra-thin.svg
  packages/base/core/src/svg/thin/lightbulb_extra-thin.svg
  packages/base/core/src/svg/thin/list_extra-thin.svg
  packages/base/core/src/svg/thin/location_extra-thin.svg
  packages/base/core/src/svg/thin/minus_extra-thin.svg
  packages/base/core/src/svg/thin/ok_extra-thin.svg
  packages/base/core/src/svg/thin/phone_extra-thin.svg
  packages/base/core/src/svg/thin/plus_extra-thin.svg
  packages/base/core/src/svg/thin/refresh_extra-thin.svg
  packages/base/core/src/svg/thin/settings_extra-thin.svg
  packages/base/core/src/svg/thin/time_extra-thin.svg
  packages/base/core/src/svg/thin/triangle-down_extra-thin.svg
  packages/base/core/src/svg/thin/triangle-left_extra-thin.svg
  packages/base/core/src/svg/thin/triangle-right_extra-thin.svg
  packages/base/core/src/svg/thin/triangle-up_extra-thin.svg
  packages/base/core/src/svg/thin/user_extra-thin.svg
  packages/base/core/src/svg/thin/warning_extra-thin.svg
Labels: feature

#398 feat(tabs): allow to select active tab item
  packages/apps/workshop/stories/components/tabs.stories.js
  packages/components/tabs/README.md
  packages/components/tabs/package.json
  packages/components/tabs/src/js/item/tabs-item.controller.js
  packages/components/tabs/src/js/tabs.component.js
  packages/components/tabs/src/js/tabs.controller.js
  packages/components/tabs/src/js/tabs.html
  packages/components/tabs/src/js/tabs.spec.js
Labels: feature

#396 feat(navbar): add style for menu header container
  packages/components/navbar/src/js/menu/navbar-menu.component.js
  packages/components/navbar/src/js/menu/navbar-menu.controller.js
  packages/components/navbar/src/js/menu/navbar-menu.html
  packages/components/navbar/src/js/navbar.html
  packages/components/navbar/src/js/navbar.spec.js
  packages/components/navbar/src/js/toggler/navbar-toggler.component.js
  packages/components/navbar/src/js/toggler/navbar-toggler.html
  packages/components/navbar/src/less/navbar.less
Labels: feature

#404 feat(stepper): emit event on form submit
  packages/components/stepper/README.md
  packages/components/stepper/src/js/step-form/step-form.controller.js
Labels: feature

#408 feat(radio): add size attribute
  packages/apps/workshop/stories/components/radio.stories.js
  packages/components/radio/README.md
  packages/components/radio/src/js/radio.component.js
  packages/components/radio/src/js/radio.controller.js
  packages/components/radio/src/js/radio.spec.js
Labels: feature

#407 feat(checkbox): add size and variant attributes
  packages/apps/workshop/stories/components/checkbox.stories.js
  packages/components/checkbox/README.md
  packages/components/checkbox/src/js/checkbox.component.js
  packages/components/checkbox/src/js/checkbox.controller.js
  packages/components/checkbox/src/js/checkbox.html
  packages/components/checkbox/src/js/checkbox.spec.js
Labels: feature

#409 feat(oui-dropdown): add arrow styles for left and right placement
  packages/oui-dropdown/dropdown.less
Labels: feature

#416 style(apps.workshop.stories.content): remove extra space on icon story
  packages/apps/workshop/stories/content/icons.stories.js
Labels: enhancement

#422 fix(criteria): fix fields size to medium
  packages/components/criteria/src/js/adder/criteria-adder.html
Labels: bug

#421 fix(select): close others opened select on opening
  packages/components/select/src/js/select.controller.js
Labels: bug

#425 fix(oui-checkbox): add relative position
  packages/oui-checkbox/_mixins.less
Labels: bug
