Repository ovh/ovh-ui-kit, pull requests merged in 2019-01, with the labels that each got.

#326 Fix/navbar header
  packages/oui-navbar/_variables.less
  packages/oui-navbar/navbar.less
Labels: bug, quality check

#327 feat(oui-timepicker): add timepicker component
  packages/oui-calendar/_normalize.less
  packages/oui-calendar/_variables.less
  packages/oui-timepicker/_normalize.less
  packages/oui-timepicker/timepicker.less
  packages/oui/stylekit.less
Labels: feature, quality check ok

#328 feat: add class error into progress-tracker
  packages/oui-progress-tracker/_variables.less
  packages/oui-progress-tracker/progress-tracker.less
Labels: feature

#330 fix(oui-navbar): center aside links
  packages/oui-navbar/_mixins.less
Labels: bug

#333 fix(oui-skeleton): apply class immediately
  packages/oui-skeleton/_normalize.less
  packages/oui-skeleton/skeleton.less
Labels: enhancement, quality check ok
