Repository ovh/ovh-ui-kit, pull requests merged in 2020-08, with the labels that each got.

#650 fix(stepper): count transcluded step forms
  packages/components/stepper/src/js/step-form/step-form.controller.js
Labels: bug

#652 Docs/storybook update
  packages/apps/workshop/.storybook/main.js
  packages/apps/workshop/.storybook/preview.js
  packages/apps/workshop/package.json
  packages/apps/workshop/stories/design-system/components/calendar/calendar-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/checkbox/checkbox-webcomponent-simple.stories.js
  packages/apps/workshop/stories/design-system/components/checkbox/checkbox-webcomponent-thumbnail.stories.js
  packages/apps/workshop/stories/design-system/components/collapsible/collapsible-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/datagrid/datagrid-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/dropdown/dropdown-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/file/file-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/guide-menu/guide-menu-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/message/message-native.stories.js
  packages/apps/workshop/stories/design-system/components/password/password-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/progress/progress-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/radio/radio-webcomponent-simple.stories.js
  packages/apps/workshop/stories/design-system/components/radio/radio-webcomponent-thumbnail.stories.js
  packages/apps/workshop/stories/design-system/components/select/select-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/tabs/tabs-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/textarea/textarea-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/directives/autocomplete/autocomplete.stories.js
  packages/apps/workshop/stories/legacy/components/criteria/criteria-webcomponent.stories.js
  packages/apps/workshop/stories/legacy/components/dual-list/dual-list-webcomponent.stories.js
  packages/apps/workshop/stories/legacy/components/form-actions/form-actions-webcomponent.stories.js
  packages/apps/workshop/stories/legacy/components/header/header-webcomponent.stories.js
  packages/apps/workshop/stories/legacy/components/inline-adder/inline-adder-webcomponent.stories.js
  packages/apps/workshop/stories/legacy/components/modal/modal-webcomponent.stories.js
  packages/apps/workshop/stories/legacy/components/navbar/navbar-native.stories.js
  packages/apps/workshop/stories/legacy/components/navbar/navbar-webcomponent.stories.js
  packages/apps/workshop/stories/legacy/components/progress-tracker/progress-tracker-native.stories.js
  packages/apps/workshop/stories/legacy/components/select-picker/select-picker-webcomponent.stories.js
  packages/apps/workshop/stories/legacy/components/sidebar/sidebar-native.stories.js
  packages/apps/workshop/stories/legacy/components/skeleton/skeleton-webcomponent.stories.js
  packages/apps/workshop/stories/legacy/components/stepper/stepper-webcomponent.stories.js
  packages/apps/workshop/stories/legacy/components/tile/tile-webcomponent.stories.js
  yarn.lock
Labels: enhancement

#658 Fix/a11y action menu
  packages/apps/workshop/.storybook/main.js
  packages/apps/workshop/package.json
  packages/apps/workshop/stories/design-system/components/action-menu/action-menu-webcomponent.stories.js
  packages/components/dropdown/src/js/trigger/dropdown-trigger.controller.js
  yarn.lock
Labels: bug

#660 Feat/modal ods update
  packages/apps/workshop/stories/design-system/components/modal/modal-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/modal/modal.story.mdx
  packages/base/core/src/css/tokens/_colors.css
  packages/base/core/src/less/tokens/_colors.less
  packages/base/core/src/less/variables/components/modal.less
  packages/base/core/src/scss/tokens/_colors.scss
  packages/components/modal/src/js/modal.controller.js
  packages/components/modal/src/js/modal.html
  packages/components/modal/src/less/modal.less
Labels: enhancement, feature

#661 Feat/tile ods update
  packages/apps/workshop/src/index.less
  packages/apps/workshop/stories/design-system/components/tile/tile-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/tile/tile.story.mdx
  packages/base/core/src/less/variables/components/tile.less
  packages/components/tile/src/less/tile.less
Labels: enhancement, feature

#662 Feat/stepper ods update
  packages/apps/workshop/package.json
  packages/apps/workshop/stories/design-system/components/stepper/stepper-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/stepper/stepper.story.mdx
  packages/base/core/src/less/variables/components/stepper.less
  packages/components/stepper/src/less/stepper.less
  yarn.lock
Labels: enhancement, feature

#663 Feat/progress tracker ods style
  packages/apps/workshop/stories/design-system/components/progress-tracker/progress-tracker-native.stories.js
  packages/apps/workshop/stories/design-system/components/progress-tracker/progress-tracker.story.mdx
  packages/base/core/src/less/variables/components/progress-tracker.less
  packages/components/progress-tracker/src/less/progress-tracker.less
Labels: feature

#667 Docs/colors accessibility
  packages/apps/workshop/src/index.less
  packages/apps/workshop/stories/design-system/helpers/colors.stories.js
Labels: enhancement

#668 Feat/inline adder ods style
  packages/apps/workshop/stories/design-system/components/inline-adder/inline-adder-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/inline-adder/inline-adder.story.mdx
  packages/base/core/src/less/variables/components/inline-adder.less
  packages/components/inline-adder/src/js/inline-adder.html
  packages/components/inline-adder/src/less/inline-adder.less
Labels: enhancement, feature

#669 Feat/dual list ods style
  packages/apps/workshop/stories/design-system/components/dual-list/dual-list-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/dual-list/dual-list.story.mdx
  packages/base/core/src/less/variables/components/dual-list.less
  packages/components/dual-list/package.json
  packages/components/dual-list/src/js/dual-list.spec.js
  packages/components/dual-list/src/js/source/dual-list-source.html
  packages/components/dual-list/src/js/target/dual-list-target.html
  packages/components/dual-list/src/less/dual-list.less
Labels: enhancement, feature

#670 Feat/header ods style
  packages/apps/workshop/src/index.less
  packages/apps/workshop/stories/design-system/components/header/header-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/header/header.story.mdx
  packages/base/core/src/less/variables/components/header.less
  packages/components/header/src/less/header-tabs.less
Labels: bug, enhancement, feature

#671 Feat/navbar ods style
  packages/apps/workshop/stories/_data/navbar.data.json
  packages/apps/workshop/stories/design-system/components/navbar/navbar-native.stories.js
  packages/apps/workshop/stories/design-system/components/navbar/navbar-webcomponent.stories.js
  packages/apps/workshop/stories/design-system/components/navbar/navbar.story.mdx
  packages/base/core/src/less/variables/components/navbar.less
  packages/components/navbar/src/index.less
  packages/components/navbar/src/js/dropdown/navbar-dropdown.html
  packages/components/navbar/src/less/_mixins.less
  packages/components/navbar/src/less/navbar-olt.less
  packages/components/navbar/src/less/navbar.less
Labels: enhancement, feature
