Repository ovh/ovh-ui-kit, pull requests merged in 2020-07, with the labels that each got.

#632 fix(tile): update tile button padding
  packages/base/core/src/less/variables/components/tile.less
  packages/components/tile/src/less/tile.less
Labels: bug

#634 docs: update CODEOWNERS and MAINAINERS
  .github/CODEOWNERS
  MAINTAINERS
Labels: enhancement

#636 feat(navbar): add callback argument on dropdown
  packages/apps/workshop/stories/legacy/components/navbar/navbar-webcomponent.stories.js
  packages/components/navbar/src/js/dropdown/navbar-dropdown.controller.js
  packages/components/navbar/src/js/dropdown/navbar-dropdown.html
  packages/components/navbar/src/js/navbar.spec.js
Labels: feature

#637 Batch of fixes for the manager
  packages/apps/workshop/package.json
  packages/base/core/src/less/typography.less
  packages/base/core/src/less/variables/content/descriptions.less
  packages/components/dropdown/src/js/item/dropdown-item.html
  packages/components/stepper/src/js/step-form/step-form.controller.js
  packages/components/tabs/src/js/item/tabs-item.controller.js
Labels: bug

#640 fix(pagination): fix selector calculation checks
  packages/components/pagination/src/js/pagination.component.js
  packages/components/pagination/src/js/pagination.controller.js
Labels: bug

#641 feat(datagrid): allow to go to given page
  packages/components/datagrid/README.md
  packages/components/datagrid/src/js/datagrid.controller.js
  packages/components/datagrid/src/js/datagrid.directive.js
  packages/components/datagrid/src/js/datagrid.spec.js
  packages/components/datagrid/src/js/paging/datagrid-local-paging.js
  packages/components/datagrid/src/js/paging/datagrid-paging-abstract.js
  packages/components/datagrid/src/js/paging/datagrid-paging.service.js
  packages/components/datagrid/src/js/paging/datagrid-remote-paging.js
Labels: feature

#644 fix(oui-select): fix native style oui-icon position
  packages/components/select/src/less/_mixins.less
Labels: bug

#645 fix(oui.tile): inherit oui tile button line height
  packages/components/tile/src/less/tile.less
Labels: bug

#647 fix(datagrid): convert typeOptions to a string to be able to parse it
  packages/components/datagrid/src/js/datagrid-column-builder.service.js
Labels: bug
