Repository ovh/ovh-ui-kit, pull requests merged in 2020-02, with the labels that each got.

#557 feat(oui-navbar): add variant attribute on menu
  packages/oui-navbar/_mixins.less
  packages/oui-navbar/navbar.less
Labels: feature

#558 feat(navbar): add variant attribute onto menus
  .stylelintrc.json
  packages/apps/workshop/stories/components/navbar.stories.js
  packages/components/button/src/less/button.less
  packages/components/calendar/src/less/flatpickr.less
  packages/components/checkbox/src/less/checkbox.less
  packages/components/header/src/less/header-tabs.less
  packages/components/input/src/less/input-group.less
  packages/components/list/src/less/list.less
  packages/components/navbar/README.md
  packages/components/navbar/src/js/menu/navbar-menu.component.js
  packages/components/navbar/src/js/menu/navbar-menu.controller.js
  packages/components/navbar/src/js/menu/navbar-menu.html
  packages/components/navbar/src/js/navbar.spec.js
  packages/components/navbar/src/js/notification/navbar-notification.component.js
  packages/components/navbar/src/js/notification/navbar-notification.controller.js
  packages/components/navbar/src/less/_mixins.less
  packages/components/navbar/src/less/navbar.less
  packages/components/progress-tracker/src/less/progress-tracker.less
  packages/components/radio/src/less/radio-toggle-group.less
  packages/components/radio/src/less/radio.less
  packages/components/select-picker/src/less/select-picker.less
  packages/components/select/src/less/_mixins.less
  packages/components/select/src/less/select.less
  packages/components/sidebar/src/less/sidebar.less
  packages/components/switch/src/less/switch.less
Labels: feature

#564 fix(icons): increase base size for icons generator
  packages/base/core/src/fonts/oui-icons/oui-icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.html
  packages/base/core/src/fonts/oui-icons/oui-icons.json
  packages/base/core/src/fonts/oui-icons/oui-icons.woff
  packages/base/core/src/fonts/oui-icons/oui-icons.woff2
  packages/base/core/src/less/_icons.less
  packages/base/core/src/svg/icons/_helpers/blank.svg
Labels: bug

#562 Feat/input ods update
  packages/apps/workshop/.storybook/main.js
  packages/apps/workshop/stories/v3/styles/input-group.stories.js
  packages/apps/workshop/stories/v3/styles/input.stories.js
  packages/apps/workshop/stories/v4/components/input-native-group.stories.js
  packages/apps/workshop/stories/v4/components/input-native-overlay.stories.js
  packages/apps/workshop/stories/v4/components/input-native-simple.stories.js
  packages/base/core/src/less/_variables.less
  packages/base/core/src/less/icons.less
  packages/base/core/src/less/mixins/forms.less
  packages/components/badge/src/less/badge.less
  packages/components/calendar/src/less/calendar.less
  packages/components/clipboard/src/less/clipboard.less
  packages/components/dual-list/src/less/dual-list.less
  packages/components/input/src/index.less
  packages/components/input/src/less/_mixins.less
  packages/components/input/src/less/input-group.less
  packages/components/input/src/less/input-overlay.less
  packages/components/input/src/less/input.less
  packages/components/password/src/js/password.html
  packages/components/password/src/less/password.less
  packages/components/select/src/less/_mixins.less
Labels: enhancement, feature

#565 feat(field): apply ODS theme
  packages/apps/workshop/stories/v3/components/field.stories.js
  packages/apps/workshop/stories/v4/components/field-webcomponent.stories.js
  packages/base/core/src/less/_variables.less
  packages/components/field/src/js/field.html
  packages/components/field/src/js/field.spec.js
  packages/components/field/src/less/field.less
Labels: enhancement, feature

#568 Build/update builder
  package.json
  packages/apps/builder/package.json
  packages/apps/builder/src/less/_constants.less
  packages/apps/builder/src/less/_icons.less
  packages/apps/builder/src/less/_tokens.less
  packages/apps/builder/src/less/_variables.less
  packages/apps/workshop/package.json
  packages/base/config/package.json
  packages/base/config/src/webpack.base.config.js
  packages/base/config/src/webpack.rules.js
  packages/base/test/package.json
  yarn.lock
Labels: enhancement

#567 Feat/checkbox ods update
  packages/apps/workshop/.storybook/preview.js
  packages/apps/workshop/stories/v3/components/checkbox.stories.js
  packages/apps/workshop/stories/v4/components/checkbox-webcomponent-simple.stories.js
  packages/apps/workshop/stories/v4/components/checkbox-webcomponent-thumbnail.stories.js
  packages/apps/workshop/stories/v4/content/icons.stories.js
  packages/base/core/src/fonts/oui-icons/oui-icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.html
  packages/base/core/src/fonts/oui-icons/oui-icons.json
  packages/base/core/src/fonts/oui-icons/oui-icons.woff
  packages/base/core/src/fonts/oui-icons/oui-icons.woff2
  packages/base/core/src/less/_icons.less
  packages/base/core/src/less/_variables.less
  packages/base/core/src/less/mixins/choice.less
  packages/base/core/src/svg/icons/components/checkbox-checked.svg
  packages/base/core/src/svg/icons/components/checkbox-checkmark.svg
  packages/base/core/src/svg/icons/components/checkbox-indeterminate.svg
  packages/base/core/src/svg/icons/components/checkbox-unchecked.svg
  packages/base/core/src/svg/icons/system/indeterminate.svg
  packages/components/button/src/less/button.less
  packages/components/checkbox/README.md
  packages/components/checkbox/src/index.less
  packages/components/checkbox/src/js/checkbox.component.js
  packages/components/checkbox/src/js/checkbox.controller.js
  packages/components/checkbox/src/js/checkbox.html
  packages/components/checkbox/src/js/checkbox.spec.js
  packages/components/checkbox/src/less/_mixins.less
  packages/components/checkbox/src/less/checkbox-thumbnail.less
  packages/components/checkbox/src/less/checkbox.less
  packages/components/radio/README.md
  packages/components/radio/src/js/radio.component.js
  packages/components/radio/src/js/radio.controller.js
  packages/components/radio/src/js/radio.html
  packages/components/radio/src/less/_mixins.less
  packages/components/radio/src/less/radio-thumbnail.less
  packages/components/radio/src/less/radio.less
  packages/components/select-picker/src/less/select-picker.less
Labels: enhancement, feature

#569 feat(oui-select-picker): add transclusion for label
  packages/components/select-picker/src/js/select-picker.component.js
  packages/components/select-picker/src/js/select-picker.html
Labels: feature
