Repository ovh/ovh-ui-kit, pull requests merged in 2020-11, with the labels that each got.

#702 refactor(slideshow): rework slideshow design
  packages/base/core/src/less/variables/components/slideshow.less
  packages/components/slideshow/src/js/panel/slideshow-panel.html
  packages/components/slideshow/src/js/slideshow.html
  packages/components/slideshow/src/less/slideshow.less
Labels: refactor

#704 Fix/slideshow text color
  packages/base/core/src/less/variables/components/slideshow.less
Labels: bug

#703 Release v4.4.2
  packages/base/core/src/less/variables/components/slideshow.less
  packages/components/slideshow/src/js/panel/slideshow-panel.html
  packages/components/slideshow/src/js/slideshow.html
  packages/components/slideshow/src/less/slideshow.less
Labels: release
