Repository ovh/ovh-ui-kit, pull requests merged in 2020-03, with the labels that each got.

#579 fix(select): fix states colors
  packages/components/select/src/less/select.less
Labels: bug

#578 fix(button): fix invalid calculated value
  .stylelintrc.json
  packages/base/core/src/less/variables/components/button.less
Labels: bug

#582 build: update dependencies
  package.json
  packages/apps/builder/package.json
  packages/apps/workshop/package.json
  packages/base/config/package.json
  packages/base/test/package.json
  packages/components/action-menu/package.json
  packages/components/autocomplete/package.json
  packages/components/back-button/package.json
  packages/components/button/package.json
  packages/components/calendar/package.json
  packages/components/checkbox/package.json
  packages/components/chips/package.json
  packages/components/clipboard/package.json
  packages/components/collapsible/package.json
  packages/components/criteria/package.json
  packages/components/datagrid/package.json
  packages/components/dropdown/package.json
  packages/components/dual-list/package.json
  packages/components/field/package.json
  packages/components/file/package.json
  packages/components/form-actions/package.json
  packages/components/guide-menu/package.json
  packages/components/header/package.json
  packages/components/inline-adder/package.json
  packages/components/message/package.json
  packages/components/modal/package.json
  packages/components/navbar/package.json
  packages/components/numeric/package.json
  packages/components/pagination/package.json
  packages/components/password/package.json
  packages/components/popover/package.json
  packages/components/progress/package.json
  packages/components/radio/package.json
  packages/components/search/package.json
  packages/components/select-picker/package.json
  packages/components/select/package.json
  packages/components/skeleton/package.json
  packages/components/slideshow/package.json
  packages/components/spinner/package.json
  packages/components/stepper/package.json
  packages/components/switch/package.json
  packages/components/tabs/package.json
  packages/components/textarea/package.json
  packages/components/tile/package.json
  packages/components/timepicker/package.json
  packages/components/tooltip/package.json
  yarn.lock
Labels: enhancement

#586 Minor enhancements
  AUTHORS
  CONTRIBUTING.md
  CONTRIBUTORS
  MAINTAINERS
  README.md
Labels: enhancement

#588 feat(progress): apply ODS theme
  packages/apps/workshop/stories/design-system/components/progress-native.stories.js
  packages/apps/workshop/stories/design-system/components/progress-webcomponent.stories.js
  packages/base/core/src/less/variables/components/progress.less
  packages/components/progress/src/less/progress.less
Labels: feature

#587 feat(message): apply ODS theme
  packages/apps/workshop/stories/design-system/components/message-native.stories.js
  packages/apps/workshop/stories/design-system/components/message-webcomponent.stories.js
  packages/apps/workshop/stories/legacy/components/message-native.stories.js
  packages/base/core/src/less/variables/components/message.less
  packages/components/message/src/less/_mixins.less
  packages/components/message/src/less/message.less
Labels: feature

#583 feat(tooltip): apply ODS theme
  package.json
  packages/apps/workshop/src/index.less
  packages/apps/workshop/stories/design-system/directives/tooltip.stories.js
  packages/apps/workshop/stories/legacy/directives/tooltip.stories.js
  packages/base/core/src/less/variables/components/tooltip.less
  packages/components/tooltip/src/js/tooltip.html
  packages/components/tooltip/src/less/_mixins.less
  packages/components/tooltip/src/less/tooltip.less
Labels: feature

#590 feat(popover): apply ODS theme
  packages/apps/workshop/stories/design-system/directives/popover.stories.js
  packages/apps/workshop/stories/design-system/directives/tooltip.stories.js
  packages/apps/workshop/stories/legacy/directives/popover.stories.js
  packages/base/core/src/less/_mixins.less
  packages/base/core/src/less/_variables.less
  packages/base/core/src/less/mixins/tooltip.less
  packages/base/core/src/less/variables/components/popover.less
  packages/base/core/src/less/variables/shared/tooltip.less
  packages/components/field/src/js/field.html
  packages/components/popover/src/js/popover.controller.js
  packages/components/popover/src/js/popover.html
  packages/components/popover/src/less/popover.less
  packages/components/tooltip/src/js/tooltip.html
  packages/components/tooltip/src/less/tooltip.less
Labels: feature

#591 feat(switch): apply ODS theme
  packages/apps/workshop/stories/design-system/components/switch-webcomponent.stories.js
  packages/apps/workshop/stories/legacy/components/switch-webcomponent.stories.js
  packages/base/core/src/less/variables/components/switch.less
  packages/components/switch/src/less/switch.less
Labels: feature

#592 feat(numeric): apply ODS theme
  packages/apps/workshop/stories/design-system/components/numeric-webcomponent.stories.js
  packages/apps/workshop/stories/legacy/components/numeric-webcomponent.stories.js
  packages/base/core/src/less/variables/components/numeric.less
  packages/components/field/src/less/field.less
  packages/components/input/src/less/input-group.less
  packages/components/numeric/src/js/numeric.controller.js
  packages/components/numeric/src/js/numeric.html
  packages/components/numeric/src/less/numeric.less
Labels: feature
