Repository ovh/ovh-ui-kit, pull requests merged in 2020-01, with the labels that each got.

#537 Feat/add readme to stories
  packages/apps/workshop/package.json
  packages/apps/workshop/stories/components/action-menu.stories.js
  packages/apps/workshop/stories/components/back-button.stories.js
  packages/apps/workshop/stories/components/button.stories.js
  packages/apps/workshop/stories/components/calendar.stories.js
  packages/apps/workshop/stories/components/checkbox.stories.js
  packages/apps/workshop/stories/components/chips.stories.js
  packages/apps/workshop/stories/components/clipboard.stories.js
  packages/apps/workshop/stories/components/collapsible.stories.js
  packages/apps/workshop/stories/components/criteria.stories.js
  packages/apps/workshop/stories/components/datagrid.stories.js
  packages/apps/workshop/stories/components/dropdown.stories.js
  packages/apps/workshop/stories/components/dual-list.stories.js
  packages/apps/workshop/stories/components/field.stories.js
  packages/apps/workshop/stories/components/file.stories.js
  packages/apps/workshop/stories/components/form-actions.stories.js
  packages/apps/workshop/stories/components/guide-menu.stories.js
  packages/apps/workshop/stories/components/header.stories.js
  packages/apps/workshop/stories/components/inline-adder.stories.js
  packages/apps/workshop/stories/components/message.stories.js
  packages/apps/workshop/stories/components/modal.stories.js
  packages/apps/workshop/stories/components/navbar.stories.js
  packages/apps/workshop/stories/components/numeric.stories.js
  packages/apps/workshop/stories/components/pagination.stories.js
  packages/apps/workshop/stories/components/password.stories.js
  packages/apps/workshop/stories/components/progress.stories.js
  packages/apps/workshop/stories/components/radio.stories.js
  packages/apps/workshop/stories/components/search.stories.js
  packages/apps/workshop/stories/components/select-picker.stories.js
  packages/apps/workshop/stories/components/select.stories.js
  packages/apps/workshop/stories/components/skeleton.stories.js
  packages/apps/workshop/stories/components/slideshow.stories.js
  packages/apps/workshop/stories/components/spinner.stories.js
  packages/apps/workshop/stories/components/stepper.stories.js
  packages/apps/workshop/stories/components/switch.stories.js
  packages/apps/workshop/stories/components/tabs.stories.js
  packages/apps/workshop/stories/components/textarea.stories.js
  packages/apps/workshop/stories/components/tile.stories.js
  packages/apps/workshop/stories/components/timepicker.stories.js
  packages/components/calendar/README.md
  packages/components/datagrid/README.md
Labels: enhancement

#538 fix(oui-dropdown): afterClose should remove the focus
  packages/components/dropdown/src/js/trigger/dropdown-trigger.controller.js
Labels: bug

#539 fix(calendar): dynamic changes for min and max date
  packages/components/calendar/src/js/calendar.controller.js
Labels: enhancement

#540 fix(collapsible): add helper to remove html on heading
  packages/base/core/src/js/component-utils.js
  packages/components/collapsible/src/js/collapsible.controller.js
  packages/components/collapsible/src/js/collapsible.html
Labels: enhancement

#541 feat(radio-toggle-group): add column direction
  packages/apps/workshop/stories/components/radio.stories.js
  packages/base/core/src/less/_variables.less
  packages/components/radio/README.md
  packages/components/radio/src/js/toggle-group/radio-toggle-group.component.js
  packages/components/radio/src/less/radio-toggle-group.less
Labels: feature

#544 fix(oui-datagrid): use lodash hasIn to check properties
  packages/components/datagrid/src/js/datagrid.controller.js
  packages/components/datagrid/src/js/paging/datagrid-paging-abstract.js
  packages/components/datagrid/src/js/util.js
Labels: enhancement

#543 feat(oui-radio-toggle-group): add column direction
  packages/oui-radio-toggle-group/radio-toggle-group.less
Labels: feature

#546 Feat/collapsible loading v2.x
  packages/oui-collapsible/collapsible.less
Labels: feature
