Repository ovh/ovh-ui-kit, pull requests merged in 2020-10, with the labels that each got.

#690 fix(tile): add padding for tile responsive
  packages/base/core/src/less/variables/components/tile.less
  packages/components/tile/src/less/tile.less
Labels: bug

#692 fix(header): change detection for scroll right
  packages/components/header/src/js/tabs/header-tabs.controller.js
Labels: bug

#693 New release
  CONTRIBUTORS
  MAINTAINERS
  packages/base/core/src/less/variables/components/tile.less
  packages/components/header/src/js/tabs/header-tabs.controller.js
  packages/components/tile/src/less/tile.less
Labels: release

#694 Back button - pass full sentence
  packages/apps/workshop/stories/design-system/components/back-button/back-button-webcomponent.stories.js
  packages/components/back-button/README.md
  packages/components/back-button/src/js/back-button.controller.js
  packages/components/back-button/src/js/back-button.provider.js
Labels: bug

#697 fix(field): allow to check if status is invalid outside of a form
  packages/components/field/src/js/field.controller.js
Labels: bug

#695 feat(icons): add PlatformSh and cloud essential icons
  packages/apps/workshop/stories/design-system/content/icons.stories.js
  packages/base/core/src/css/tokens/_icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.html
  packages/base/core/src/fonts/oui-icons/oui-icons.json
  packages/base/core/src/fonts/oui-icons/oui-icons.woff
  packages/base/core/src/fonts/oui-icons/oui-icons.woff2
  packages/base/core/src/less/tokens/_icons.less
  packages/base/core/src/less/variables/generated/icons.less
  packages/base/core/src/scss/tokens/_icons.scss
  packages/base/core/src/svg/icons/concept/cloud-essential_concept.svg
  packages/base/core/src/svg/icons/concept/partner-platformsh_concept.svg
Labels: feature, quality check ok

#698 Release v4.4.0
  packages/apps/workshop/stories/design-system/content/icons.stories.js
  packages/base/core/src/css/tokens/_icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.html
  packages/base/core/src/fonts/oui-icons/oui-icons.json
  packages/base/core/src/fonts/oui-icons/oui-icons.woff
  packages/base/core/src/fonts/oui-icons/oui-icons.woff2
  packages/base/core/src/less/tokens/_icons.less
  packages/base/core/src/less/variables/generated/icons.less
  packages/base/core/src/scss/tokens/_icons.scss
  packages/base/core/src/svg/icons/concept/cloud-essential_concept.svg
  packages/base/core/src/svg/icons/concept/partner-platformsh_concept.svg
  packages/components/field/src/js/field.controller.js
Labels: release

#700 fix(typography): add default pointer-event property on links
  packages/base/core/src/less/mixins/typography.less
Labels: bug, enhancement

#701 Release v4.4.1
  packages/base/core/src/less/mixins/typography.less
Labels: release
