Repository ovh/ovh-ui-kit, pull requests merged in 2021-08, with the labels that each got.

#730 fix(oui.back-button): remove deprecated translation key
  packages/components/back-button/README.md
  packages/components/back-button/src/js/back-button.provider.js
Labels: bug

#728 Release v5.0.0
  packages/apps/workshop/stories/design-system/content/icons.stories.js
  packages/base/core/src/css/tokens/_icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.html
  packages/base/core/src/fonts/oui-icons/oui-icons.json
  packages/base/core/src/fonts/oui-icons/oui-icons.woff
  packages/base/core/src/fonts/oui-icons/oui-icons.woff2
  packages/base/core/src/less/tokens/_icons.less
  packages/base/core/src/less/variables/generated/icons.less
  packages/base/core/src/scss/tokens/_icons.scss
  packages/base/core/src/svg/icons/concept/trusted_concept.svg
  packages/components/back-button/README.md
  packages/components/back-button/src/js/back-button.provider.js
  packages/components/badge/src/less/badge.less
  packages/components/button/src/less/button.less
  packages/components/checkbox/src/less/checkbox-thumbnail.less
  packages/components/chips/src/less/chips.less
  packages/components/datagrid/src/less/_mixins.less
  packages/components/navbar/src/js/dropdown/navbar-dropdown.html
  packages/components/navbar/src/js/menu/navbar-menu.html
  packages/components/navbar/src/less/navbar.less
  packages/components/radio/src/less/radio-thumbnail.less
  packages/components/tile/src/less/tile.less
Labels: release

#732 feat(icons): add nutanix icon
  packages/apps/workshop/stories/design-system/content/icons.stories.js
  packages/base/core/src/css/tokens/_icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.html
  packages/base/core/src/fonts/oui-icons/oui-icons.json
  packages/base/core/src/fonts/oui-icons/oui-icons.woff
  packages/base/core/src/fonts/oui-icons/oui-icons.woff2
  packages/base/core/src/less/tokens/_icons.less
  packages/base/core/src/less/variables/generated/icons.less
  packages/base/core/src/scss/tokens/_icons.scss
  packages/base/core/src/svg/icons/concept/nutanix_concept.svg
Labels: feature
