Repository ovh/ovh-ui-kit, pull requests merged in 2021-07, with the labels that each got.

#721 fix(config): prevent processing svg as html
  packages/base/config/src/webpack.rules.js
Labels: bug

#722 New release v4.6.1
  packages/base/config/src/webpack.rules.js
Labels: release

#725 feat(icons): add enterprise file storage icon
  packages/apps/workshop/stories/design-system/content/icons.stories.js
  packages/base/core/src/css/tokens/_icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.html
  packages/base/core/src/fonts/oui-icons/oui-icons.json
  packages/base/core/src/fonts/oui-icons/oui-icons.woff
  packages/base/core/src/fonts/oui-icons/oui-icons.woff2
  packages/base/core/src/less/tokens/_icons.less
  packages/base/core/src/less/variables/generated/icons.less
  packages/base/core/src/scss/tokens/_icons.scss
  packages/base/core/src/svg/icons/concept/enterprise-file-storage_concept.svg
Labels: enhancement

#726 Release v4.6.2
  packages/apps/workshop/stories/design-system/content/icons.stories.js
  packages/base/core/src/css/tokens/_icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.html
  packages/base/core/src/fonts/oui-icons/oui-icons.json
  packages/base/core/src/fonts/oui-icons/oui-icons.woff
  packages/base/core/src/fonts/oui-icons/oui-icons.woff2
  packages/base/core/src/less/tokens/_icons.less
  packages/base/core/src/less/variables/generated/icons.less
  packages/base/core/src/scss/tokens/_icons.scss
  packages/base/core/src/svg/icons/concept/enterprise-file-storage_concept.svg
Labels: release

#712 feat: add trusted icon
  packages/apps/workshop/stories/design-system/content/icons.stories.js
  packages/base/core/src/css/tokens/_icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.css
  packages/base/core/src/fonts/oui-icons/oui-icons.html
  packages/base/core/src/fonts/oui-icons/oui-icons.json
  packages/base/core/src/fonts/oui-icons/oui-icons.woff
  packages/base/core/src/fonts/oui-icons/oui-icons.woff2
  packages/base/core/src/less/tokens/_icons.less
  packages/base/core/src/less/variables/generated/icons.less
  packages/base/core/src/scss/tokens/_icons.scss
  packages/base/core/src/svg/icons/concept/trusted_concept.svg
Labels: bug

#724 fix(oui.navbar): remove vulnerable ng-bind-html
  packages/components/navbar/src/js/dropdown/navbar-dropdown.html
  packages/components/navbar/src/js/menu/navbar-menu.html
Labels: breaking-change, bug

#729 refactor(*): remove deprecated less class
  packages/components/badge/src/less/badge.less
  packages/components/button/src/less/button.less
  packages/components/checkbox/src/less/checkbox-thumbnail.less
  packages/components/chips/src/less/chips.less
  packages/components/datagrid/src/less/_mixins.less
  packages/components/navbar/src/less/navbar.less
  packages/components/radio/src/less/radio-thumbnail.less
  packages/components/tile/src/less/tile.less
Labels: refactor
